name: Python application

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]

    strategy:
      max-parallel: 4
      fail-fast: true
      matrix:
        python: [2.7.x, 3.4.x, 3.5.x, 3.6.x, 3.7.x, 3.8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip install -r requirements.txt
        
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#     - name: Test with pytest
#       run: |
#         pip install pytest
#         pytest

    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.13.0

    - name: Check Django warnings
      run: python app/manage.py check
